In [19]:
#importing the numpy package
import numpy as np

In [106]:
def npa(*argv):
    return np.array(argv)

In [30]:
#initilizing the numbers
a = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='int8')

b = np.array([1,2,3],dtype='float16')

In [32]:
#size gives the size of the array => total numbers of the elements of the array
print(a.size)

#shape gives the total dimentionality of the array
print(a.shape)

#ndims gives the no of dimensions required
print(a.ndim)

#datatype of the array
print(a.dtype)

9
(3, 3)
2
int8


In [63]:
#indexing

a[:,:]  # gives the total matrix
a[1,2]  # gives the 2nd row and 3rd element
a[1,:]  # gives the ith row
a[:,1]  # gives the jth column
a[1,1::1]

array([5, 6], dtype=int8)

In [62]:
#let a be the matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='int8')
#the transpose of the matrix is defines as
tp_a = np.array([a[:,i] for i in range(a.shape[1])])

print(tp_a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [49]:
#gives the zeros matrix of size 3
np.zeros((2,3),dtype='int8')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [54]:
#gives the ones matrix as the size

np.ones((2,3),dtype='int8')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [56]:
#gives the Identity matrix of size n

np.identity(3,dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [60]:
#gives the matrix of shape mentioned filled with the number
np.full((3,4),4)

#gives the matrix same as full with shape of "a"
np.full_like(a,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int8)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int8)

In [78]:
#random numbers 
np.random.rand() #gives a random number 0-1
np.random.rand(5,6) #gives the random numbers array 0-1
np.random.randint(-14,5,size=(3,3)) #random numbers between -14 to 5 in size of (3,3)
np.random.randint(-5,5,(2,2,2))

array([[[ 3,  3],
        [ 4, -1]],

       [[ 4,  1],
        [ 3,  4]]])

In [83]:
#gives the output of n times repeating a

a = [[1,2,3]]
np.repeat(a,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [107]:
#us ecopy to copy the contents of a to b

a = npa(1,2,3)
b = a.copy()
b[1] = 1

print(a,b)

[1 2 3] [1 1 3]


In [109]:
a = npa(1,2,3)
a + 2
a - 2
a * 2
a / 2
a // 2

array([0, 1, 1], dtype=int32)

In [115]:
b = npa(4,5,6)
a + b
a / b
a // b
a ** b

array([  1,  32, 729], dtype=int32)

In [118]:
np.cos(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

In [127]:
a = np.ones((2,3))
b = np.full((3,2),2)

np.matmul(a,b)
np.linalg.det(np.matmul(a,b))

0.0

In [142]:
a = np.array([[1,2,3],[4,5,6]])
np.mean(a,axis=0)
np.max(a,axis=0)
np.min(a,axis=1)
np.sum(a,axis=1)


array([ 6, 15])